[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
source_gui = { path = "../source_gui" }
rune_ui = { path = "../rune_ui" }
futures = "0.3.28"
eframe = { version = "0.24.1", features = [
    "__screenshot", # __screenshot is so we can dump a screenshot using EFRAME_SCREENSHOT_TO
] }
kv-log-macro = "1.0.7"
femme = "2.2.1"
